spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/db_vvshow?characterEncoding=utf-8&useSSL=false
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      max-active: 50
      min-idle: 10
      max-wait: 10
      default-auto-commit: true
      min-evictable-idle-time-millis: 3600000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
    mapperLocations: classpath:dao/*.xml
